* Architecture
#+BEGIN_SRC text
  early_init.el
       |
   def-confs.el   -----(when -fo flag)----->   fo-confs.el
       |                                           |
       |                                           |
       |                                           |
 k-packaging.el                                    |
       |                                           |
       |                                           |
 extra-majors.el                                   |
       |                                           |
       |-------------------         ---------------|
       |                  |         |
  k-<major>.el        k-<major>-defs.el
  k-<major>.el        k-<major>-defs.el
      ...                 |         |
       | ------------------          ------------- |
       |                                           |
       |                                           |
   START EMACS                                START EMACS
#+END_SRC

** early_init.el
- Boot performance (ex: grabadge collection, startup ui configurations)
- Some variables defining like =kadir/emacs-fast-open fast-open= or =kadir/default-font-size=.

** def-confs.el - Default Configurations
Default Emacs settings, keybindings and function. Without any package.
- Except major-mode settings like org-mode.

** fo-configs.el - Fast Open Configurations
Ido-mode like default emacs packages loading. I will not use them as a my primary configurations but for fast oppen, it is good solutions.

** k-packaging.el - Pacage Initializing
It has package installers (=straight.el=, =use-pacakge=), or very generic packages (=no-littering=).
** extra-majors.el
Extra file related major modes (like magit has major modes but it is not file related major mode).
- Except directly extended major modes (like web-mode is extended directly html mode or js2-mode extended directly js mode).
- =restclient=, =json-mode=, =saas-mode=, =yaml-mode=, =docker-compose-mode=, =dockefile-mode=, =pdf-tools=, =ein=, =terraform-mode=
** minors
Minors are minor modes that I wrote. These are basic minor modes that wraps some of minor-mode packages for a purpose.

For instance I wrote _k-flysyntx-mode_ minor mode. It wraps flycheck mode and flymake mode at the same time. Basicly It wraps them and create a single api so when I want to use its on any major mode, I don't need to worry about keybinding difference. It basicly create keybindings for which activated mode.

Or _k-colors-mode_ minor mode wraps popular coloring packages which are for extra syntax coloring. There is so much package and some times I want to disable all of them. For this minor mode I don't have to remember all theese package names and I can toggle all of them at once. And also I think all of keybingins could be similar with each other, this minor makes it happen.
